# Generated by Django 2.1.5 on 2021-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='distribution_area',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='brief',
            field=models.TextField(),
        ),
    ]
